package view;

import control.KendaraanControl;
import exception.InputKosongException;
import exception.IdErrorException;
import exception.JenisErrorException;
import exception.NotNumberException;
import java.lang.NumberFormatException;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import model.Kendaraan;

public class KendaraanView extends javax.swing.JFrame {

    /**
     * Creates new form KendaraanView
     */
    private KendaraanControl kendaraanControl;
    String action = null;
    public KendaraanView() {
        initComponents();
        setComponent(false);
        setEditDeleteBtn(false);
        kendaraanControl = new KendaraanControl();
        showKendaraan();
    }
    
    // method untuk set komponen input dan button save, button cancel
    public void setComponent(boolean value){
        idInput.setEnabled(value);
        modelInput.setEnabled(value);
        tahunPembuatanInput.setEnabled(value);
        nomorPlatInput.setEnabled(value);
        penumpangInput.setEnabled(value);
        dayaAngkutInput.setEnabled(value);
        mobilButton.setEnabled(value);
        trukButton.setEnabled(value);
        
        saveBtn.setEnabled(value);
        cancelBtn.setEnabled(value);
    }
    
    // method untuk set komponen button edit dan delete button
    public void setEditDeleteBtn(boolean value){
        editBtn.setEnabled(value);
        deleteBtn.setEnabled(value);
    }
    
    // method untuk set value text dari komponen input
    public void clearText(){
        idInput.setText("");
        modelInput.setText("");
        tahunPembuatanInput.setText("");
        nomorPlatInput.setText("");
        penumpangInput.setText("");
        dayaAngkutInput.setText("");
        searchInput.setText("");
        
    }
    
    public void showKendaraan(){
        showMobil.setText(kendaraanControl.showDataKendaraan());
    }
    
    public void inputKosongException() throws InputKosongException{
        if(idInput.getText().isEmpty() || modelInput.getText().isEmpty() || tahunPembuatanInput.getText().isEmpty() || nomorPlatInput.getText().isEmpty()){
            throw new InputKosongException();
        }
    }
    
    public void idErrorException() throws IdErrorException{
        if(idInput.getText().length() < 5 || idInput.getText().length() >8){
            throw new IdErrorException();
            
        }
    }
    
    public void jenisErrorException() throws JenisErrorException{
        if(jenisButtonGroup.getSelection()==null){
            throw new JenisErrorException();
        }
    }
    
    public void notNumberException() throws NotNumberException{
        throw new NotNumberException();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisButtonGroup = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        sidebarPanel = new javax.swing.JPanel();
        lecturerPanel = new javax.swing.JPanel();
        lecturerLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        containerPanel = new javax.swing.JPanel();
        titleContent = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        searchInput = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        containerInputDayaAngkut = new javax.swing.JPanel();
        dayaAngkutLabel = new javax.swing.JLabel();
        dayaAngkutInput = new javax.swing.JTextField();
        containerInputNomorPlat = new javax.swing.JPanel();
        nomorPlatLabel = new javax.swing.JLabel();
        nomorPlatInput = new javax.swing.JTextField();
        containerInputNama = new javax.swing.JPanel();
        modelLabel = new javax.swing.JLabel();
        modelInput = new javax.swing.JTextField();
        containerInputId = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        idInput = new javax.swing.JTextField();
        containerInputTahunPembuatan = new javax.swing.JPanel();
        tahunPembuatanLabel = new javax.swing.JLabel();
        tahunPembuatanInput = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        containerInputPenumpang = new javax.swing.JPanel();
        penumpangLabel = new javax.swing.JLabel();
        penumpangInput = new javax.swing.JTextField();
        mobilButton = new javax.swing.JRadioButton();
        trukButton = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        showMobil = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lecturerLabel.setText("Kendaraan");

        javax.swing.GroupLayout lecturerPanelLayout = new javax.swing.GroupLayout(lecturerPanel);
        lecturerPanel.setLayout(lecturerPanelLayout);
        lecturerPanelLayout.setHorizontalGroup(
            lecturerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lecturerPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lecturerLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lecturerPanelLayout.setVerticalGroup(
            lecturerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lecturerPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lecturerLabel)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lecturerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(lecturerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        titleContent.setText("Kendaraan");

        addBtn.setText("Tambah");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        editBtn.setText("Ubah");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Hapus");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        searchBtn.setText("Cari");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        dayaAngkutLabel.setText("Daya Angkut");

        dayaAngkutInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayaAngkutInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerInputDayaAngkutLayout = new javax.swing.GroupLayout(containerInputDayaAngkut);
        containerInputDayaAngkut.setLayout(containerInputDayaAngkutLayout);
        containerInputDayaAngkutLayout.setHorizontalGroup(
            containerInputDayaAngkutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputDayaAngkutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerInputDayaAngkutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dayaAngkutLabel)
                    .addComponent(dayaAngkutInput, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containerInputDayaAngkutLayout.setVerticalGroup(
            containerInputDayaAngkutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputDayaAngkutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dayaAngkutLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dayaAngkutInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
        );

        nomorPlatLabel.setText("Nomor Plat");

        nomorPlatInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomorPlatInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerInputNomorPlatLayout = new javax.swing.GroupLayout(containerInputNomorPlat);
        containerInputNomorPlat.setLayout(containerInputNomorPlatLayout);
        containerInputNomorPlatLayout.setHorizontalGroup(
            containerInputNomorPlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputNomorPlatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerInputNomorPlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomorPlatLabel)
                    .addComponent(nomorPlatInput, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        containerInputNomorPlatLayout.setVerticalGroup(
            containerInputNomorPlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputNomorPlatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomorPlatLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomorPlatInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
        );

        modelLabel.setText("Nama Model");

        modelInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerInputNamaLayout = new javax.swing.GroupLayout(containerInputNama);
        containerInputNama.setLayout(containerInputNamaLayout);
        containerInputNamaLayout.setHorizontalGroup(
            containerInputNamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputNamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerInputNamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modelLabel)
                    .addComponent(modelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        containerInputNamaLayout.setVerticalGroup(
            containerInputNamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputNamaLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(modelLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 37, Short.MAX_VALUE))
        );

        idLabel.setText("Id Kendaraan");

        idInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerInputIdLayout = new javax.swing.GroupLayout(containerInputId);
        containerInputId.setLayout(containerInputIdLayout);
        containerInputIdLayout.setHorizontalGroup(
            containerInputIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputIdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerInputIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idLabel)
                    .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        containerInputIdLayout.setVerticalGroup(
            containerInputIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputIdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tahunPembuatanLabel.setText("Tahun Pembuatan");

        tahunPembuatanInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunPembuatanInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerInputTahunPembuatanLayout = new javax.swing.GroupLayout(containerInputTahunPembuatan);
        containerInputTahunPembuatan.setLayout(containerInputTahunPembuatanLayout);
        containerInputTahunPembuatanLayout.setHorizontalGroup(
            containerInputTahunPembuatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputTahunPembuatanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerInputTahunPembuatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tahunPembuatanLabel)
                    .addComponent(tahunPembuatanInput, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        containerInputTahunPembuatanLayout.setVerticalGroup(
            containerInputTahunPembuatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputTahunPembuatanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tahunPembuatanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tahunPembuatanInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        saveBtn.setText("Simpan");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Batal");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        penumpangLabel.setText("Penumpang");

        penumpangInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penumpangInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerInputPenumpangLayout = new javax.swing.GroupLayout(containerInputPenumpang);
        containerInputPenumpang.setLayout(containerInputPenumpangLayout);
        containerInputPenumpangLayout.setHorizontalGroup(
            containerInputPenumpangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputPenumpangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerInputPenumpangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(penumpangLabel)
                    .addComponent(penumpangInput, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containerInputPenumpangLayout.setVerticalGroup(
            containerInputPenumpangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputPenumpangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(penumpangLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(penumpangInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        jenisButtonGroup.add(mobilButton);
        mobilButton.setText("Mobil");
        mobilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilButtonActionPerformed(evt);
            }
        });

        jenisButtonGroup.add(trukButton);
        trukButton.setText("Truk");
        trukButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trukButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        showMobil.setEditable(false);
        showMobil.setBackground(new java.awt.Color(255, 255, 255));
        showMobil.setColumns(20);
        showMobil.setRows(5);
        jScrollPane1.setViewportView(showMobil);

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(containerPanelLayout.createSequentialGroup()
                                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(containerPanelLayout.createSequentialGroup()
                                        .addComponent(containerInputId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(100, 100, 100)
                                        .addComponent(mobilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(titleContent)
                                    .addGroup(containerPanelLayout.createSequentialGroup()
                                        .addComponent(addBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(editBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(deleteBtn)
                                        .addGap(137, 137, 137)
                                        .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(searchBtn)))
                                .addGap(98, 98, 98))
                            .addGroup(containerPanelLayout.createSequentialGroup()
                                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(containerPanelLayout.createSequentialGroup()
                                        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(containerInputNomorPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(containerInputTahunPembuatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(65, 65, 65)
                                        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(containerInputPenumpang, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(containerInputDayaAngkut, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(containerPanelLayout.createSequentialGroup()
                                        .addComponent(containerInputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(108, 108, 108)
                                        .addComponent(trukButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(103, 103, 103))
                                    .addComponent(saveBtn))
                                .addGap(18, 18, 18)
                                .addComponent(cancelBtn))))
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 734, Short.MAX_VALUE))
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleContent)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBtn)
                            .addComponent(editBtn)
                            .addComponent(deleteBtn)
                            .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBtn))
                        .addGap(18, 18, 18)
                        .addComponent(containerInputId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(containerPanelLayout.createSequentialGroup()
                                .addComponent(containerInputPenumpang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(trukButton))
                            .addComponent(containerInputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(containerPanelLayout.createSequentialGroup()
                                .addComponent(containerInputTahunPembuatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(containerInputNomorPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(containerInputDayaAngkut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(mobilButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(cancelBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(242, 242, 242))
        );

        jScrollPane2.setViewportView(containerPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        setComponent(false);
        setEditDeleteBtn(false);
        clearText();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        try{
            inputKosongException();
            idErrorException();
            jenisErrorException();
            notNumberException();
            
            
            mobilButton.setActionCommand("Mobil");
            trukButton.setActionCommand("Truk");
            
            Kendaraan d = new Kendaraan();
            
            if(jenisButtonGroup.getSelection().getActionCommand().compareTo("Mobil")==0){
                
                if(penumpangInput.getText().isEmpty()){
                    throw new InputKosongException();
                }
                try{
                    Integer.parseInt(penumpangInput.getText());
                    d = new Kendaraan(idInput.getText(), modelInput.getText(), jenisButtonGroup.getSelection().getActionCommand(), Integer.valueOf(tahunPembuatanInput.getText()), nomorPlatInput.getText(), Integer.valueOf(penumpangInput.getText()), 0);    
                }catch(NumberFormatException e){
                    throw new NotNumberException();
                }
                
                
            }else{
                if(dayaAngkutInput.getText().isEmpty()){
                    throw new InputKosongException();
                }
                
                try{
                    Integer.parseInt(dayaAngkutInput.getText());
                    d = new Kendaraan(idInput.getText(), modelInput.getText(), jenisButtonGroup.getSelection().getActionCommand(), Integer.valueOf(tahunPembuatanInput.getText()), nomorPlatInput.getText(), 0, Float.valueOf(dayaAngkutInput.getText()));        
                }catch(NumberFormatException e){
                    throw new NotNumberException();
                }
                
            }

            if(action.equals("Tambah")){
                kendaraanControl.insertDataKendaraan(d);
            }else{
                kendaraanControl.updateDataKendaraan(d, idInput.getText());
            }
            clearText();
            showKendaraan();
            setComponent(false);
            setEditDeleteBtn(false);
        }catch(InputKosongException e){
            JOptionPane.showMessageDialog(this, e.message());
        }catch(IdErrorException e){
            JOptionPane.showMessageDialog(this, e.message());
        }catch(JenisErrorException e){
            JOptionPane.showMessageDialog(this, e.message());
        }catch(NotNumberException e){
            JOptionPane.showMessageDialog(this, e.message());
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void tahunPembuatanInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunPembuatanInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahunPembuatanInputActionPerformed

    private void idInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idInputActionPerformed

    private void modelInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelInputActionPerformed

    private void nomorPlatInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomorPlatInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomorPlatInputActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        setEditDeleteBtn(true);
        setComponent(false);

        try{
            Kendaraan kendaraan = kendaraanControl.searchKendaraan(searchInput.getText());

            if(kendaraan == null){
                clearText();
                setEditDeleteBtn(false);
                JOptionPane.showConfirmDialog(null, "Data tidak ditemukan", "Konfirmasi", JOptionPane.DEFAULT_OPTION);
            }else{
                
                idInput.setText(kendaraan.getId());
                modelInput.setText(kendaraan.getModel());
                
                if(kendaraan.getDayaAngkut()!=0){
                    dayaAngkutInput.setText(String.valueOf(kendaraan.getDayaAngkut()));
                    trukButton.setSelected(true);
                    
                }

                tahunPembuatanInput.setText(String.valueOf(kendaraan.getTahunPembuatan()));
                nomorPlatInput.setText(kendaraan.getNoPlat());
                

            }
        }catch(Exception e){
            System.out.println("Error : "+e.getMessage());
        }

    }//GEN-LAST:event_searchBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Apakah yakin ingin menghapus data ? ", "Konfirmasi", JOptionPane.YES_NO_OPTION);

        if(getAnswer == JOptionPane.YES_OPTION){
            try{
                kendaraanControl.deleteDataKendaraan(idInput.getText());
                clearText();
                showKendaraan();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
            }catch(Exception e){
                System.out.println("Error : "+e.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Data tidak jadi dihapus!");
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        setComponent(true);
        idInput.setEnabled(true);
        action = "Ubah";
    }//GEN-LAST:event_editBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // ketika button tambah diklik, maka akan aktifkan komponen input
        setComponent(true);
        clearText();
        
        penumpangInput.setEnabled(false);
        dayaAngkutInput.setEnabled(false);
        
        searchInput.setText("");
        action = "Tambah";
    }//GEN-LAST:event_addBtnActionPerformed

    private void dayaAngkutInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayaAngkutInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayaAngkutInputActionPerformed

    private void penumpangInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penumpangInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penumpangInputActionPerformed

    private void mobilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobilButtonActionPerformed
        penumpangInput.setEnabled(true);
        dayaAngkutInput.setEnabled(false);
        dayaAngkutInput.setText("");
    }//GEN-LAST:event_mobilButtonActionPerformed

    private void trukButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trukButtonActionPerformed
        dayaAngkutInput.setEnabled(true);
        penumpangInput.setEnabled(false);
        penumpangInput.setText("");
    }//GEN-LAST:event_trukButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KendaraanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KendaraanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KendaraanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KendaraanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KendaraanView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel containerInputDayaAngkut;
    private javax.swing.JPanel containerInputId;
    private javax.swing.JPanel containerInputNama;
    private javax.swing.JPanel containerInputNomorPlat;
    private javax.swing.JPanel containerInputPenumpang;
    private javax.swing.JPanel containerInputTahunPembuatan;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JTextField dayaAngkutInput;
    private javax.swing.JLabel dayaAngkutLabel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JTextField idInput;
    private javax.swing.JLabel idLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.ButtonGroup jenisButtonGroup;
    private javax.swing.JLabel lecturerLabel;
    private javax.swing.JPanel lecturerPanel;
    private javax.swing.JRadioButton mobilButton;
    private javax.swing.JTextField modelInput;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JTextField nomorPlatInput;
    private javax.swing.JLabel nomorPlatLabel;
    private javax.swing.JTextField penumpangInput;
    private javax.swing.JLabel penumpangLabel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchInput;
    private javax.swing.JTextArea showMobil;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JTextField tahunPembuatanInput;
    private javax.swing.JLabel tahunPembuatanLabel;
    private javax.swing.JLabel titleContent;
    private javax.swing.JRadioButton trukButton;
    // End of variables declaration//GEN-END:variables
}
